# Generated by Django 4.2.16 on 2026-03-16 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='', max_length=200)),
                ('sender_address', models.TextField(default='')),
                ('sender_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('client_name', models.CharField(default='', max_length=200)),
                ('client_phone', models.CharField(blank=True, default='', max_length=50)),
                ('client_email', models.EmailField(blank=True, default='', max_length=254)),
                ('client_address', models.TextField(blank=True, default='')),
                ('invoice_number', models.IntegerField(default=1)),
                ('invoice_date', models.DateField()),
                ('currency', models.CharField(default='$', max_length=5)),
                ('terms', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='SenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.TextField(default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('default_currency', models.CharField(default='$', max_length=5)),
                ('default_terms', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Sender Profile',
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
